# Generated by Django 5.2.14 on 2026-07-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pago_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcial'), ('por_vencer', 'Por vencer'), ('vencido', 'Vencido')], default='pendiente', max_length=12),
        ),
    ]
