# Generated by Django 5.2.14 on 2026-07-07 14:53

from django.db import migrations, models


def backfill_fecha_vencimiento(apps, schema_editor):
    Pago = apps.get_model('pagos', 'Pago')
    Pago.objects.update(fecha_vencimiento=models.F('fecha_pago'))


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_alter_pago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.RunPython(backfill_fecha_vencimiento, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
    ]
