# Generated by Django 5.2.14 on 2026-07-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_contrato_contratos_c_estado_608720_idx'),
        ('pagos', '0005_pago_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='pagos_pago_estado_0f9a87_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='pagos_pago_fecha_p_af939d_idx'),
        ),
    ]
