[mypy]
python_version = 3.11
plugins = mypy_django_plugin.main, mypy_drf_plugin.main

# Gradual typing: permisivo en esta fase, se endurece progresivamente
strict = false
warn_return_any = true
warn_unused_ignores = true
no_implicit_optional = true
ignore_missing_imports = true

# Excluir archivos que no se tipan manualmente
exclude = migrations/|manage\.py|settings/|asgi\.py|wsgi\.py

[mypy.plugins.django-stubs]
django_settings_module = config.settings.local
