# Generated by Django 5.2.14 on 2026-05-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('moroso', 'Moroso')], default='activo', max_length=12)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='habitaciones.habitacion')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='inquilinos.inquilino')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'ordering': ['-created_at'],
            },
        ),
    ]
