# Generated by Django 5.2.14 on 2026-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='deposito',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='monto_mensual',
            field=models.PositiveIntegerField(),
        ),
    ]
