# Generated by Django 5.2.14 on 2026-07-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contrato_fecha_fin_not_null'),
        ('habitaciones', '0004_habitacion_deleted_at_tipohabitacion_deleted_at_and_more'),
        ('inquilinos', '0002_inquilino_deleted_at_alter_inquilino_documento_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado'], name='contratos_c_estado_608720_idx'),
        ),
    ]
