# Generated by Django 5.2.14 on 2026-07-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_contrato_contratos_c_estado_608720_idx'),
        ('habitaciones', '0004_habitacion_deleted_at_tipohabitacion_deleted_at_and_more'),
        ('inquilinos', '0002_inquilino_deleted_at_alter_inquilino_documento_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['activo', 'moroso'])), fields=('habitacion',), name='unique_contrato_habitacion_activo'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['activo', 'moroso'])), fields=('inquilino',), name='unique_contrato_inquilino_activo'),
        ),
    ]
