# Generated by Django 5.2.14 on 2026-06-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], max_length=10),
        ),
    ]
