# Generated by Django 5.2.14 on 2026-05-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('piso', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad', models.PositiveIntegerField(default=1)),
                ('tiene_banio_privado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'habitación',
                'verbose_name_plural': 'habitaciones',
                'ordering': ['piso', 'numero'],
            },
        ),
    ]
