# Generated by Django 5.2.14 on 2026-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
