# Generated by Django 5.2.14 on 2026-06-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_alter_habitacion_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.PositiveIntegerField()),
                ('capacidad', models.PositiveIntegerField(default=1)),
                ('tiene_banio_privado', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de habitación',
                'verbose_name_plural': 'tipos de habitación',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitaciones', to='habitaciones.tipohabitacion'),
        ),
    ]
