# Generated by Django 5.2.14 on 2026-06-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_tipohabitacion_habitacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='habitacion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('numero',), name='unique_habitacion_numero_active'),
        ),
        migrations.AddConstraint(
            model_name='tipohabitacion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('nombre',), name='unique_tipohabitacion_nombre_active'),
        ),
    ]
