# Generated by Django 5.2.14 on 2026-06-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='inquilino',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('email',), name='unique_inquilino_email_active'),
        ),
        migrations.AddConstraint(
            model_name='inquilino',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('documento',), name='unique_inquilino_documento_active'),
        ),
    ]
